[package]
name = "gomoku-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
axum = "0.8.1"
tokio = { version = "1.43.0", features = ["macros", "rt-multi-thread"] }
serde = { version = "1.0.217", features = ["derive"]}
