version: '3.8'

x-common:
  &common
  build: server
  image: gomoku
  environment:
    LOG_LEVEL: "INFO"

services:
  server:
    <<: *common
    command: ["uvicorn",  "src.app:create_app", "--port", "8000", "--host", "0.0.0.0"]
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8000/healthz"]
      interval: 10s
      timeout: 5s
      retries: 3
    restart: always
    ports:
      - "8000:8000"

  ui:
    build: client
    image: gomoku-ui
    healthcheck:
      test: [ "CMD", "service", "nginx", "status" ]
      interval: 10s
      retries: 3
    restart: always
    ports:
      - "80:80"
    depends_on:
      - server
