version: '3.8'

services:
  server:
    build: gomoku-rs
    image: gomoku-rs
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8000/healthz"]
      interval: 10s
      timeout: 5s
      retries: 3
    restart: always
    ports:
      - "8000:8000"
    environment:
      PORT: 8000

  ui:
    build: client
    image: gomoku-ui
    healthcheck:
      test: [ "CMD", "service", "nginx", "status" ]
      interval: 10s
      retries: 3
    restart: always
    ports:
      - "80:80"
    depends_on:
      - server
