name: CI Build

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:

  unit-tests:
    timeout-minutes: 5
    name: Unit-tests
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: "."

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        name: setup-python
        with:
          python-version: "3.10"
          architecture: "x64"
      - name: Install dependencies
        run: pip install -r requirements.txt -r requirements-test.txt
        working-directory: ./server
      - name: Run pytest with coverage
        run: make test